<?php

namespace App\Http\Controllers;

use App\Http\Requests\UserRequest;
use App\Models\User;
use Illuminate\Support\Facades\Hash;
use Tenant\Acl\Role;
use Tenant\Http\AbstractController;
use Tenant\ManagerTenant;

class UserController extends AbstractController
{
   protected $model = User::class;

   protected $route = "users";

   protected $template = "users";

   public function index()
   {
       $this->model->where('tenant_id', app(ManagerTenant::class)->getTenantIdentify());

       return parent::index();
   }

   public function create()
   {
       $this->results['roles'] = Role::all();

       return parent::create(); // TODO: Change the autogenerated stub
   }

    public function edit($id)
   {
       $this->results['roles'] = Role::all();

       return parent::edit($id); // TODO: Change the autogenerated stub
   }

    public function store(UserRequest $request)
    {

        return parent::_store($request);
    }


    public function update(UserRequest $request, $id)
    {
        return parent::_update($request, $id);
    }

    protected function preEvent($model, $request)
    {
        if ($request->has('password') && !$request->input('password') ){
            unset( $this->data['password']);
        }
        else{
            $this->data['password'] = Hash::make($this->data['password']);
        }

        $this->data['tenant_id'] = app(ManagerTenant::class)->getTenantIdentify();
    }

    protected function posEvent($model, $request)
    {
        if($request->has('roles'))
            $model->roles()->sync($request->get('roles'));
    }
}
